import React from "react";
import { motion } from "framer-motion";

const stats = [
  { value: "99%", label: "of the world's largest companies are SAP customers" },
  { value: "87%", label: "of total global commerce is generated by SAP customers" },
  { value: "280M+", label: "cloud users leveraging SAP solutions globally" },
  { value: "100+", label: "innovation centers across the world" }
];

const Stats = () => {
  return (
    <section className="py-20 bg-slate-900 relative overflow-hidden">
      <div className="absolute inset-0 bg-blue-600/10 pointer-events-none" />
      <div className="max-w-7xl mx-auto px-6 md:px-12 relative z-10">
        <div className="grid grid-cols-2 md:grid-cols-4 gap-8 md:gap-12 text-center">
          {stats.map((stat, i) => (
            <motion.div
              key={i}
              initial={{ opacity: 0, scale: 0.8 }}
              whileInView={{ opacity: 1, scale: 1 }}
              viewport={{ once: true }}
              transition={{ delay: i * 0.1 }}
            >
              <h3 className="text-4xl md:text-6xl font-black text-white mb-4">
                <span className="text-transparent bg-clip-text bg-gradient-to-r from-blue-400 to-cyan-300">
                  {stat.value}
                </span>
              </h3>
              <p className="text-slate-300 text-sm md:text-base font-medium">{stat.label}</p>
            </motion.div>
          ))}
        </div>
      </div>
    </section>
  );
};

export default Stats;
